config/routes.rb
Save::Application.routes.draw do
  resources :courses

  resources :training_calendars do
    resources :trainees
  end
  match 'training_calendars/:id/start' => 'training_calendars#start', :via => :get
  match 'training_calendars/:id/end' => 'training_calendars#end', :via => :get
  match 'training_calendars/:id/attendance' => 'training_calendars#attendance', :via => :get

  resources :users

  resource :dashboard

  resources :participants

  resources :training_centers

  resources :programs

  root :to => 'login#show'

  match 'login' => 'login#create', :via => :post

  match 'logout' => 'login#destroy', :via => :get

end

app/models/training_center.rb
class TrainingCenter < ActiveRecord::Base
  validates_uniqueness_of :name
  validates_presence_of :name, :district, :state, :pin_code

  def label
    name + " in " + district + " district of " + state
  end
end

app/controllers/training_centers_controller.rb
class TrainingCentersController < ApplicationController
  # GET /training_centers
  # GET /training_centers.json
  def index
    @training_centers = TrainingCenter.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @training_centers }
    end
  end

  # GET /training_centers/1
  # GET /training_centers/1.json
  def show
    @training_center = TrainingCenter.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @training_center }
    end
  end

  # GET /training_centers/new
  # GET /training_centers/new.json
  def new
    @training_center = TrainingCenter.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @training_center }
    end
  end

  # GET /training_centers/1/edit
  def edit
    @training_center = TrainingCenter.find(params[:id])
  end

  # POST /training_centers
  # POST /training_centers.json
  def create
    @training_center = TrainingCenter.new(params[:training_center])

    respond_to do |format|
      if @training_center.save
        format.html { redirect_to @training_center, :notice => 'Training center was successfully created.' }
        format.json { render :json => @training_center, :status => :created, :location => @training_center }
      else
        format.html { render :action => "new" }
        format.json { render :json => @training_center.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /training_centers/1
  # PUT /training_centers/1.json
  def update
    @training_center = TrainingCenter.find(params[:id])

    respond_to do |format|
      if @training_center.update_attributes(params[:training_center])
        format.html { redirect_to @training_center, :notice => 'Training center was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @training_center.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /training_centers/1
  # DELETE /training_centers/1.json
  def destroy
    @training_center = TrainingCenter.find(params[:id])
    @training_center.destroy

    respond_to do |format|
      format.html { redirect_to training_centers_url }
      format.json { head :ok }
    end
  end
end

app/views/training_centers/_form.html.erb
<%= form_for(@training_center) do |f| %>
  <% if @training_center.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@training_center.errors.count, "error") %> prohibited this training_center from being saved:</h2>

      <ul>
      <% @training_center.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/training_centers/edit.html.erb
<h1>Editing training_center</h1>

<%= render 'form' %>

<%= link_to 'Show', @training_center %> |
<%= link_to 'Back', training_centers_path %>

app/views/training_centers/index.html.erb
<h1>Listing training_centers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @training_centers.each do |training_center| %>
  <tr>
    <td><%= link_to 'Show', training_center %></td>
    <td><%= link_to 'Edit', edit_training_center_path(training_center) %></td>
    <td><%= link_to 'Destroy', training_center, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Training center', new_training_center_path %>

app/views/training_centers/new.html.erb
<h1>New training_center</h1>

<%= render 'form' %>

<%= link_to 'Back', training_centers_path %>

app/views/training_centers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_training_center_path(@training_center) %> |
<%= link_to 'Back', training_centers_path %>