config/routes.rb
Save::Application.routes.draw do
  resources :courses

  resources :training_calendars do
    resources :trainees
  end
  match 'training_calendars/:id/start' => 'training_calendars#start', :via => :get
  match 'training_calendars/:id/end' => 'training_calendars#end', :via => :get
  match 'training_calendars/:id/attendance' => 'training_calendars#attendance', :via => :get

  resources :users

  resource :dashboard

  resources :participants

  resources :training_centers

  resources :programs

  root :to => 'login#show'

  match 'login' => 'login#create', :via => :post

  match 'logout' => 'login#destroy', :via => :get

end

app/models/training_calendar.rb
class TrainingCalendar < ActiveRecord::Base
  belongs_to :training_center
  belongs_to :course
  has_many :trainees

  validates_presence_of :training_center_id, :course_id, :batch_size, :start_date, :end_date
  validates_numericality_of :batch_size

  NOT_STARTED = "Not Started"

  def status_message
    parts = status.split(/_/)
    parts.each { |part| part.capitalize! }
    parts.join(" ")
  end
end

app/controllers/training_calendars_controller.rb
class TrainingCalendarsController < ApplicationController
  # GET /training_calendars
  # GET /training_calendars.json
  def index
    @training_calendars = TrainingCalendar.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @training_calendars }
    end
  end

  # GET /training_calendars/1
  # GET /training_calendars/1.json
  def show
    @training_calendar = TrainingCalendar.find(params[:id])
    @trainees          = Trainee.find_all_by_training_calendar_id(@training_calendar.id)
    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @training_calendar }
    end
  end

  # GET /training_calendars/new
  # GET /training_calendars/new.json
  def new
    load_dependents
    @training_calendar = TrainingCalendar.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @training_calendar }
    end
  end

  # GET /training_calendars/1/edit
  def edit
    load_dependents
    @training_calendar = TrainingCalendar.find(params[:id])
  end

  # POST /training_calendars
  # POST /training_calendars.json
  def create
    @training_calendar        = TrainingCalendar.new(params[:training_calendar])
    @training_calendar.status = TrainingCalendar::NOT_STARTED
    respond_to do |format|
      if @training_calendar.save
        format.html { redirect_to @training_calendar, :notice => 'Training calendar was successfully created.' }
        format.json { render :json => @training_calendar, :status => :created, :location => @training_calendar }
      else
        load_dependents
        format.html { render :action => "new" }
        format.json { render :json => @training_calendar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /training_calendars/1
  # PUT /training_calendars/1.json
  def update
    @training_calendar = TrainingCalendar.find(params[:id])
    respond_to do |format|
      if @training_calendar.update_attributes(params[:training_calendar])
        format.html { redirect_to @training_calendar, :notice => 'Training calendar was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @training_calendar.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /training_calendars/1
  # DELETE /training_calendars/1.json
  def destroy
    @training_calendar = TrainingCalendar.find(params[:id])
    @training_calendar.destroy

    respond_to do |format|
      format.html { redirect_to training_calendars_url }
      format.json { head :ok }
    end
  end

  def start
    change_training_status({:status => "In-Progress"})
  end

  def end
    change_training_status({:status => "Ended"})
  end

  def attendance
    @training_calendar = TrainingCalendar.find(params[:id])    
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  def change_training_status(attrs)
    @training_calendar = TrainingCalendar.find(params[:id])
    respond_to do |format|
      if @training_calendar.update_attributes(attrs)
        format.html { redirect_to @training_calendar }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @training_calendar.errors, :status => :unprocessable_entity }
      end
    end
  end


  def load_dependents
    @training_centers = TrainingCenter.all
    @courses          = Course.all
  end
end

app/views/training_calendars/_form.html.erb
<%= form_for(@training_calendar, :html => {:class => "well form-horizontal"}) do |form| %>
    <fieldset>
      <% if @training_calendar.errors.any? %>
          <div id="error_explanation" class="well-small alert alert-error">
            <h4>
              <%= pluralize(@training_calendar.errors.count, "error") %>
              prevented this training calendar from being saved:
            </h4>
            <ul>
              <% @training_calendar.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="control-group">
        <label class="control-label" for="select01">Select Training Center</label>

        <div class="controls">
          <%= form.select("training_center_id", @training_centers.collect { |center| [center.label, center.id] },
                          {:include_blank => true}, {:class => "input-xlarge"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="select01">Select Course</label>

        <div class="controls">
          <%= form.select("course_id", @courses.collect { |course| [course.label, course.id] },
                          {:include_blank => true}, {:class => "input-xlarge"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input01">Batch Size</label>

        <div class="controls">
          <%= form.text_field(:batch_size, {:class => "input-mini"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input01">Starting on</label>

        <div class="controls">
          <%= form.text_field(:start_date, {"class "=>"small", "data-datepicker" => "datepicker"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input01">Ending on</label>

        <div class="controls">
          <%= form.text_field(:end_date, {"class "=>"small", "data-datepicker" => "datepicker"}) %>
          <span class="help-block"> Dates are in <strong>MM/DD/YYYY</strong> format </span>
        </div>
      </div>

      <span class="help-block"> All fields are mandatory</span>

      <div class="form-actions">
        <%= form.submit("Save Calendar", {"class"=> "btn btn-primary"}) %>
        <%= link_to 'Cancel', training_calendars_path, :class => "btn btn-inverse" %>
      </div>
    </fieldset>
<% end %>

<script>
    /* Update datepicker plugin so that MM/DD/YYYY format is used. */
    $.extend($.fn.datepicker.defaults, {
        parse: function (string) {
            var matches;
            if ((matches = string.match(/^(\d{2,2})\/(\d{2,2})\/(\d{4,4})$/))) {
                return new Date(matches[3], matches[1] - 1, matches[2]);
            } else {
                return null;
            }
        },
        format: function (date) {
            var
                    month = (date.getMonth() + 1).toString(),
                    dom = date.getDate().toString();
            if (month.length === 1) {
                month = "0" + month;
            }
            if (dom.length === 1) {
                dom = "0" + dom;
            }
            return month + "/" + dom + "/" + date.getFullYear();
        }
    });
</script>

app/views/training_calendars/_participants.html.erb
<div class="form-horizontal">
  <fieldset>
    <legend>Participants</legend>
    <br/>
    <table class="table table-bordered table-striped table-condensed">
      <thead>
      <th>#Id</th>
      <th>First name</th>
      <th>Actions</th>
      </thead>
      <tbody>
      <% @trainees.each do |trainee| %>
          <tr>
            <td><%= trainee.id %></td>
            <td><%= link_to(trainee.full_name, participant_path(trainee.participant_id)) %></td>
            <td>Remove</td>
          </tr>
      <% end %>
      </tbody>
    </table>
  </fieldset>
</div>

app/views/training_calendars/_subnav.html.erb
<div class="subnav">
  <ul class="nav nav-pills">
    <li><%= link_to 'Edit', edit_training_calendar_path(@training_calendar) %></li>
    <li><%= link_to 'Add Participants', new_training_calendar_trainee_path(@training_calendar) %></li>
    <li><%= link_to 'Start Training', "/training_calendars/#{@training_calendar.id}/start" %> </li>
    <li><%= link_to 'End Training', "/training_calendars/#{@training_calendar.id}/end" %> </li>
    <li><%= link_to 'Track Attendance', "/training_calendars/#{@training_calendar.id}/attendance" %></li>
    <li><%= link_to 'All Calendars', training_calendars_path %></li>
  </ul>
</div>

<br/>

app/views/training_calendars/attendance.html.erb
<%= render :partial => 'subnav' %>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <th>Participant</th>
  <% 30.times do |i| %>
      <th>Day <%= i+1 %></th>
  <% end %>
  </thead>

  <tbody>

  <% 25.times do %>
      <tr>
        <td>Name</td>
        <% 30.times do %>
            <td>P</td>
        <% end %>
      </tr>
  <% end %>

  </tbody>
</table>

app/views/training_calendars/edit.html.erb
<div class="page-header">
  <h3>Editing Calendar for <%= @training_calendar.training_center.label %></h3>
</div>

<div class="alert alert-info">
  <span>The status of this training : <strong><%= @training_calendar.status_message %></strong></span>
</div>

<%= render 'form' %>

<%= link_to 'Show', @training_calendar %> |
<%= link_to 'Back', training_calendars_path %>

app/views/training_calendars/index.html.erb
<div class="page-header">
  <div class="row">
    <div class="span4"><h3><span class="small">Training Calendars</span></h3></div>
    <%= link_to 'Create a new calendar', new_training_calendar_path, :class => "btn btn-primary" %>
  </div>

</div>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <th>#Id</th>
  <th>Training Duration</th>
  <th>Training Center</th>
  <th>CVET Course</th>
  </thead>

  <tbody>
  <% @training_calendars.each do |training_calendar| %>
      <tr>
        <td><%= training_calendar.id %></td>
        <td>
          <a href="<%= training_calendar_path(training_calendar) %>"><strong><%= training_calendar.start_date %> to <%= training_calendar.end_date %></strong></a>
        </td>
        <td><%= link_to training_calendar.training_center.name, training_calendar.training_center %></td>
        <td><%= link_to training_calendar.course.name, training_calendar.course %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/training_calendars/new.html.erb
<div class="page-header">
  <div class="row">
    <div class="span4"><h3><span class="small">Create a new training calendar</span></h3></div>
    <%= link_to 'View all training calendars', training_calendars_path, :class => "btn btn-primary" %>
  </div>

</div>


<%= render 'form' %>

app/views/training_calendars/show.html.erb
<% unless notice.nil? then %>
    <div id="notice" class="alert alert-success">
      <%= notice %> <a class="close" data-dismiss="alert" href="#">&times;</a>
    </div>
<% end %>

<%= render :partial => 'subnav' %>

<div class="alert alert-info">
  <span>The status of this training : <strong><%= @training_calendar.status_message %></strong></span>
</div>

<div class="well form-horizontal">
  <fieldset>
    <legend>Calendar for <%= @training_calendar.training_center.label %></legend>
    <div class="control-group">
      <label class="control-label" for="select01">Training Center</label>

      <div class="controls">
        <label class="control-label" for="select01">
          <%= link_to(@training_calendar.training_center.name, @training_calendar.training_center) %>
        </label>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Course</label>

      <div class="controls">
        <label class="control-label">
          <%= link_to(@training_calendar.course.name, @training_calendar.course) %>
        </label>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Batch Size</label>

      <div class="controls">
        <label class="control-label">
          <%= @training_calendar.batch_size %>
        </label>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Start Date</label>

      <div class="controls">
        <label class="control-label">
          <%= @training_calendar.start_date %>
        </label>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">End Date</label>

      <div class="controls">
        <label class="control-label">
          <%= @training_calendar.end_date %>
        </label>
      </div>
    </div>

  </fieldset>
</div>


<%= render :partial => 'participants' %>