config/routes.rb
Save::Application.routes.draw do
  resources :courses

  resources :training_calendars do
    resources :trainees
  end
  match 'training_calendars/:id/start' => 'training_calendars#start', :via => :get
  match 'training_calendars/:id/end' => 'training_calendars#end', :via => :get
  match 'training_calendars/:id/attendance' => 'training_calendars#attendance', :via => :get

  resources :users

  resource :dashboard

  resources :participants

  resources :training_centers

  resources :programs

  root :to => 'login#show'

  match 'login' => 'login#create', :via => :post

  match 'logout' => 'login#destroy', :via => :get

end

app/models/participant.rb
class Participant < ActiveRecord::Base

  validates_presence_of :first_name, :last_name, :village_id, :address_line_1, :status, :gender
  validates_numericality_of :pin_code, :age

  belongs_to :village

  def activate_now
    self.status = "Active"
  end

  def full_name
    first_name + " " + last_name
  end

  def assign
    self.status = "Assigned"
    save
  end

end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  # GET /participants
  # GET /participants.json
  def index
    @participants = Participant.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @participants }
    end
  end

  # GET /participants/1
  # GET /participants/1.json
  def show
    @participant = Participant.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @participant }
    end
  end

  # GET /participants/new
  # GET /participants/new.json
  def new
    load_dependencies
    @participant = Participant.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @participant }
    end
  end

  def load_dependencies
    @villages = Village.all
  end

  # GET /participants/1/edit
  def edit
    @participant = Participant.find(params[:id])
    load_dependencies
  end

  # POST /participants
  # POST /participants.json
  def create
    @participant = Participant.new(params[:participant])
    @participant.activate_now
    respond_to do |format|
      if @participant.save
        format.html { redirect_to @participant, :notice => 'Participant was successfully created.' }
        format.json { render :json => @participant, :status => :created, :location => @participant }
      else
        load_dependencies
        format.html { render :action => "new" }
        format.json { render :json => @participant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /participants/1
  # PUT /participants/1.json
  def update
    @participant = Participant.find(params[:id])

    respond_to do |format|
      if @participant.update_attributes(params[:participant])
        format.html { redirect_to @participant, :notice => 'Participant was successfully updated.' }
        format.json { head :ok }
      else
        load_dependencies
        format.html { render :action => "edit" }
        format.json { render :json => @participant.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /participants/1
  # DELETE /participants/1.json
  def destroy
    @participant = Participant.find(params[:id])
    @participant.destroy

    respond_to do |format|
      format.html { redirect_to participants_url }
      format.json { head :ok }
    end
  end
end

app/views/participants/_form.html.erb
<%= form_for(@participant, :html => {:class => "well form-horizontal"}) do |form| %>
    <fieldset>
      <% if @participant.errors.any? %>
          <div id="error_explanation" class="well-small alert alert-error">
            <h4>
              <%= pluralize(@participant.errors.count, "error") %>
              prevented this participant from being saved:
            </h4>
            <ul>
              <% @participant.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
      <% end %>


      <div class="control-group">
        <label class="control-label" for="input01">First Name</label>

        <div class="controls">
          <%= form.text_field(:first_name, {:class => "input-large"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input01">Last Name</label>

        <div class="controls">
          <%= form.text_field(:last_name, {:class => "input-large"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input01">Age</label>

        <div class="controls">
          <%= form.text_field(:age, {:class => "input-mini"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input01">Gender</label>

        <div class="controls">
          <%= form.select("gender", [["Female", "Female"], ["Male", "Male"]],
                          {:class => "input-xlarge"}) %>

        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input01">Address Line 1</label>

        <div class="controls">
          <%= form.text_field(:address_line_1, {:class => "input-large"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input01">Address Line 2</label>

        <div class="controls">
          <%= form.text_field(:address_line_2, {:class => "input-large"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input01">Address Line 3</label>

        <div class="controls">
          <%= form.text_field(:address_line_3, {:class => "input-large"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input01">Address Line 4</label>

        <div class="controls">
          <%= form.text_field(:address_line_4, {:class => "input-large"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="select03">Village</label>

        <div class="controls">
          <%= form.select("village_id", @villages.collect { |village| [village.name, village.id] },
                          {:include_blank => true}, {:class => "input-xlarge"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input01">Pin Code</label>

        <div class="controls">
          <%= form.text_field(:pin_code, {:class => "input-large"}) %>
        </div>
      </div>

      <div class="control-group">
        <label class="control-label" for="input01">Comments</label>

        <div class="controls">
          <%= form.text_area(:comments, {:class => "input-large"}) %>
        </div>
      </div>


      <span class="help-block"> All fields are mandatory</span>

      <div class="form-actions">
        <%= form.submit("Save Participant", {"class"=> "btn btn-primary"}) %>
        <%= link_to 'Cancel', participants_path, :class => "btn btn-inverse" %>
      </div>
    </fieldset>
<% end %>

app/views/participants/edit.html.erb
<h1>Editing participant</h1>

<%= render 'form' %>

<%= link_to 'Show', @participant %> |
<%= link_to 'Back', participants_path %>

app/views/participants/index.html.erb
<div class="page-header">
  <div class="row">
    <div class="span4"><h3><span class="small">Participants</span></h3></div>
    <%= link_to 'Add a new participant', new_participant_path, :class => "btn btn-primary" %>
  </div>

</div>

<table class="table table-striped table-bordered table-condensed">
  <thead>
  <th>#Id</th>
  <th>First name</th>
  <th>Actions</th>
  </thead>

  <tbody>
  <% @participants.each do |participant| %>
      <tr>
        <td><%= participant.id %></td>
        <td><%= link_to (participant.first_name + " " + participant.last_name), participant %></td>
        <td><%= link_to 'Edit', edit_participant_path(participant) %>
          | <%= link_to 'Delete', participant, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
  <% end %>
  </table>

app/views/participants/new.html.erb
<div class="page-header">
  <div class="row">
    <div class="span4"><h3><span class="small">Create a new participant</span></h3></div>
    <%= link_to 'View all participants', participants_path, :class => "btn btn-primary" %>
  </div>

</div>

<%= render 'form' %>

<%= link_to 'Back', participants_path %>

app/views/participants/show.html.erb
<% unless notice.nil? then %>
    <div id="notice" class="alert alert-success">
      <%= notice %> <a class="close" data-dismiss="alert" href="#">&times;</a>
    </div>
<% end %>

<div class="well form-horizontal">
  <fieldset>
    <legend>Details for <%= @participant.first_name %>,<%= @participant.last_name %></legend>

    <div class="control-group">
      <label class="control-label">First name</label>

      <div class="controls">
        <label class="control-label">
          <%= @participant.first_name %>
        </label>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Last name</label>

      <div class="controls">
        <label class="control-label">
          <%= @participant.last_name %>
        </label>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Age</label>

      <div class="controls">
        <label class="control-label">
          <%= @participant.age %>
        </label>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Gender</label>

      <div class="controls">
        <label class="control-label">
          <%= @participant.gender %>
        </label>
      </div>
    </div>

    <div class="control-group">
      <label class="control-label">Address</label>

      <div class="controls">
        <address>
          <%= @participant.address_line_1 %>
          <%= @participant.address_line_2 %>
          <%= @participant.address_line_3 %>
          <%= @participant.address_line_4 %>
          <br/>
          <%= @participant.pin_code %>
          <br/>
          <%= @participant.village.name %>
          <br/>
          <%= @participant.village.district.name %> District
          <br/>
          <%= @participant.village.district.state.name %>
        </address>
      </div>
    </div>

    <div class="alert alert-info">
      <%= @participant.comments %>
    </div>

  </fieldset>
</div>

<%= link_to 'Edit', edit_participant_path(@participant) %> |
<%= link_to 'Back', participants_path %>